- name: copy prometheus config file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: copy rules
  ansible.builtin.template:
    src: Health_rules.yml
    dest: /opt/prometheus/Health_rules.yml

- name: copy rules
  ansible.builtin.template:
    src: Resource_rules.yml
    dest: /opt/prometheus/Resource_rules.yml

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes

- name: copy alert manager configuration file
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Restart alert-manager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
    enabled: yes