variable "env" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "app_tags" {}
variable "subnets" {}
variable "bastion_cidr" {}
variable "sub_ids" {}
variable "app_port" {}
variable "component" {}
variable "instance_type" {}
variable "min_count" {}
variable "max_count" {}