route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'Amazon-SNS'
receivers:
  - name: 'Amazon-SNS'
    sns_configs:
      - sigv4_config:
          region: us-east-1
        topic_arn: arn:aws:sns:us-east-1:180933357369:Prometheus-alertmanager
        subject: "frontend health"