route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'Amazon-SNS'
receivers:
  - name: 'Amazon-SNS'
    sns_configs:
      - sigv4:
          region: us-east-1
        topic_arn: arn:aws:sns:us-east-1:180933357369:Prometheus-alertmanager
        subject: "frontend health"

  - name: 'Amazon-SES'
    email_configs:
      to: prabhavith99@gmail.com
      from: prabhavith99@gmail.com
      smarthost: "email-smtp.us-east-1.amazonaws.com:587"
      auth_username: "AKIASUIDX544RE5FERGI"
      auth_password: "BCp03qxaa9SQGUzyfSCKQ/PCvjFpuxmXuERoBA7ivnZ7"
      require_tls: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
