groups:
  - name: Health group
    rules:
      - alert: Not reachable
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          #label1 : abc
          #label2 :xyz and so on
        annotations:
          summary: Server is down