groups:
  - name: Resource consumption
    rules:
      - alert: Ram high
        expr: (node_memory_MemFree_bytes / node_memory_MemTotal_bytes) * 100 > 50
        for: 1m
        labels:
          severity: warning
          {% raw %}
        annotations:
          summary: "Ram of  {{ $labels.instance }} is high"
          {% endraw %}
          description: !unsafe "Ram consumption of {{ $labels.instance }} is at {{$value}} percentage"